// SysManager · SystemReportServiceTests
// Author: laurentiu021 · https://github.com/laurentiu021/SystemManager
// License: MIT

using System.Text.Json;
using SysManager.Shared.Models;
using SysManager.Shared.Services;

namespace SysManager.Tests;

/// <summary>
/// Tests for <see cref="SystemReportService"/>'s pure formatters (text / HTML / JSON).
/// These render a deterministic <see cref="SystemReportData"/> fixture, so they need no
/// WMI access and run identically on CI. The data-gathering path (GenerateDataAsync) hits
/// live WMI and is intentionally not unit-tested here.
/// </summary>
public class SystemReportServiceTests
{
    private static SystemReportData Sample(
        IReadOnlyList<GpuReportInfo>? gpus = null,
        string? motherboard = null,
        IReadOnlyList<DiskReportInfo>? disks = null,
        IReadOnlyList<NetworkAdapterInfo>? adapters = null) => new(
            GeneratedAt: new DateTime(2026, 1, 2, 13, 14, 15, DateTimeKind.Local),
            AppVersion: "1.20.68",
            Os: new OsInfo("Windows 11 Pro", "10.0.22631", "22631", TimeSpan.FromHours(50), "64-bit"),
            Cpu: new CpuInfo("Intel Core i7-12700K", 12, 20, 5000, 18.0),
            Memory: new MemoryInfo(32, 16, 16, 50, [new MemoryModule("DIMM0", "Corsair", 16, 3200, 2400, "PN1")]),
            Gpus: gpus ?? [new GpuReportInfo("NVIDIA RTX 4070", 12.0, "551.86")],
            Motherboard: motherboard ?? "ASUS ROG STRIX Z690",
            Disks: disks ?? [new DiskReportInfo("Samsung 980 PRO", "SSD", "NVMe", 1000, "Healthy", "Healthy — 38 °C", 38.0, 5, "1.4y")],
            NetworkAdapters: adapters ?? [new NetworkAdapterInfo("Intel I225-V", "192.168.1.10", "AA-BB-CC-DD-EE-FF", true)]);

    // ---------- BuildText ----------

    [Fact]
    public void BuildText_ContainsHeaderAndFooterWithVersion()
    {
        var text = SystemReportService.BuildText(Sample());
        Assert.Contains("SysManager System Report", text);
        Assert.Contains("Generated: 2026-01-02 13:14:15", text);
        Assert.Contains("Generated by SysManager v1.20.68", text);
    }

    [Fact]
    public void BuildText_ContainsAllSectionTitles()
    {
        var text = SystemReportService.BuildText(Sample());
        foreach (var title in new[] { "Operating System", "CPU", "Memory", "GPU", "Motherboard", "Storage", "Network" })
            Assert.Contains(title, text);
    }

    [Fact]
    public void BuildText_RendersPopulatedValues()
    {
        var text = SystemReportService.BuildText(Sample());
        Assert.Contains("Windows 11 Pro", text);
        Assert.Contains("Intel Core i7-12700K", text);
        Assert.Contains("(12 cores / 20 threads)", text);
        Assert.Contains("32.0 GB total", text);
        Assert.Contains("DIMM0", text);
        Assert.Contains("NVIDIA RTX 4070", text);
        Assert.Contains("ASUS ROG STRIX Z690", text);
        Assert.Contains("Samsung 980 PRO", text);
        Assert.Contains("192.168.1.10", text);
        Assert.Contains("DHCP", text);
    }

    [Fact]
    public void BuildText_EmptyCollections_ShowFallbackLines()
    {
        var text = SystemReportService.BuildText(Sample(gpus: [], motherboard: "", disks: [], adapters: []));
        Assert.Contains("(No GPU information available)", text);
        Assert.Contains("(No motherboard information available)", text);
        Assert.Contains("(No disk information available)", text);
        Assert.Contains("(No active network adapters found)", text);
    }

    [Fact]
    public void BuildText_StaticAdapter_ShownAsStatic()
    {
        var text = SystemReportService.BuildText(Sample(
            adapters: [new NetworkAdapterInfo("Realtek", "10.0.0.5", "11-22-33-44-55-66", false)]));
        Assert.Contains("Static", text);
        Assert.DoesNotContain("— DHCP", text);
    }

    // ---------- BuildHtml ----------

    [Fact]
    public void BuildHtml_IsWellFormedDocument()
    {
        var html = SystemReportService.BuildHtml(Sample());
        Assert.StartsWith("<!DOCTYPE html>", html);
        Assert.Contains("<title>SysManager System Report</title>", html);
        Assert.EndsWith("</html>", html.TrimEnd());

        // The footer used to read "no data leaves this machine" — true of the application, and beside the
        // point at the bottom of a file whose purpose is to be sent to somebody. It now describes the FILE,
        // which is the claim a reader actually needs (#2352). The exact sentence is pinned in
        // SystemReportRedactionTests; here it is only that a footer exists at all.
        Assert.Contains("safe to share", html);
    }

    [Fact]
    public void BuildHtml_ContainsAllSections()
    {
        var html = SystemReportService.BuildHtml(Sample());
        foreach (var title in new[] { "Operating System", "CPU", "Memory", "GPU", "Motherboard", "Storage", "Network" })
            Assert.Contains($"<h2>{title}</h2>", html);
    }

    [Fact]
    public void BuildHtml_EncodesHostileDeviceNames()
    {
        // A device/adapter name containing markup must never break out of the document.
        var html = SystemReportService.BuildHtml(Sample(
            gpus: [new GpuReportInfo("<script>alert(1)</script>", null, "")]));
        Assert.DoesNotContain("<script>alert(1)</script>", html);
        Assert.Contains("&lt;script&gt;", html);
    }

    [Fact]
    public void BuildHtml_EmptyCollections_RenderPlaceholders()
    {
        var html = SystemReportService.BuildHtml(Sample(gpus: [], motherboard: "", disks: [], adapters: []));
        Assert.Contains("(none detected)", html);   // GPU + storage
        Assert.Contains("(unknown)", html);          // motherboard
        Assert.Contains("(no active adapters)", html);
    }

    // ---------- BuildJson ----------

    [Fact]
    public void BuildJson_RoundTripsToEquivalentData()
    {
        var original = Sample();
        var json = SystemReportService.BuildJson(original);
        var restored = JsonSerializer.Deserialize<SystemReportData>(json);

        Assert.NotNull(restored);
        Assert.Equal(original.AppVersion, restored!.AppVersion);
        Assert.Equal(original.Os.Caption, restored.Os.Caption);
        Assert.Equal(original.Cpu.Name, restored.Cpu.Name);
        Assert.Equal(original.Memory.TotalGB, restored.Memory.TotalGB);
        Assert.Equal(original.Gpus[0].Name, restored.Gpus[0].Name);
        Assert.Equal(original.Motherboard, restored.Motherboard);
        Assert.Equal(original.Disks[0].FriendlyName, restored.Disks[0].FriendlyName);
        Assert.Equal(original.NetworkAdapters[0].MacAddress, restored.NetworkAdapters[0].MacAddress);
    }

    [Fact]
    public void BuildJson_IsIndented()
    {
        var json = SystemReportService.BuildJson(Sample());
        Assert.Contains("\n", json);
        Assert.Contains("  ", json);
    }

    [Fact]
    public void BuildJson_RelaxedEncoding_DoesNotEscapePlusInNames()
    {
        var json = SystemReportService.BuildJson(Sample(
            gpus: [new GpuReportInfo("Notepad++ Display", null, "")]));
        Assert.Contains("Notepad++ Display", json);
        Assert.DoesNotContain("\\u002B", json);
    }

    [Fact]
    public void BuildJson_PreservesNullOptionalDiskFields()
    {
        var json = SystemReportService.BuildJson(Sample(
            disks: [new DiskReportInfo("Generic", "Unspecified", "Other", 0, "Unknown", null, null, null, null)]));
        var restored = JsonSerializer.Deserialize<SystemReportData>(json);
        Assert.Null(restored!.Disks[0].Verdict);
        Assert.Null(restored.Disks[0].TemperatureC);
        Assert.Null(restored.Disks[0].WearPercent);
        Assert.Null(restored.Disks[0].PowerOnDisplay);
    }

    [Fact]
    public void BuildJson_EmptyCollections_SerializeAsEmptyArrays()
    {
        var json = SystemReportService.BuildJson(Sample(gpus: [], disks: [], adapters: []));
        var restored = JsonSerializer.Deserialize<SystemReportData>(json);
        Assert.Empty(restored!.Gpus);
        Assert.Empty(restored.Disks);
        Assert.Empty(restored.NetworkAdapters);
    }
}
